/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Radiant Software (64-bit)
    3.2.0.18.0
    Soft IP Version: 1.4.0
    2023 11 30 15:48:56
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module multMAC (clk_i, clk_en_i, rst_i, data_a_i, data_b_i, result_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  clk_i;
    input  clk_en_i;
    input  rst_i;
    input  [15:0]  data_a_i;
    input  [15:0]  data_b_i;
    output  [31:0]  result_o;
endmodule