/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Radiant Software (64-bit)
    3.2.0.18.0
    Soft IP Version: 1.4.0
    2023 11 28 21:19:15
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module adderMac (clk_en_i, clk_i, rst_i, data_a_re_i, data_b_re_i, result_re_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  clk_en_i;
    input  clk_i;
    input  rst_i;
    input  [31:0]  data_a_re_i;
    input  [31:0]  data_b_re_i;
    output  [31:0]  result_re_o;
endmodule