-- -------------------------------------------------------------
--
-- Module: Hlp2
-- Generated by MATLAB(R) 23.2 and Filter Design HDL Coder 23.2.
-- Generated on: 2023-11-29 19:54:36
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- HDL Code Generation Options:
--
-- TargetLanguage: VHDL
-- Name: Hlp2
-- TestBenchName: Hlp2_tb
-- TestBenchStimulus: impulse step ramp chirp noise 

-- Filter Specifications:
--
-- Sample Rate     : N/A (normalized frequency)
-- Response        : Lowpass
-- Specification   : Fp,Fst,Ap,Ast
-- Passband Ripple : 1 dB
-- Stopband Edge   : 0.55
-- Stopband Atten. : 60 dB
-- Passband Edge   : 0.45
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- HDL Implementation    : Fully parallel
-- Folding Factor        : 1
-- -------------------------------------------------------------
-- Filter Settings:
--
-- Discrete-Time FIR Filter (real)
-- -------------------------------
-- Filter Structure  : Direct-Form FIR
-- Filter Length     : 43
-- Stable            : Yes
-- Linear Phase      : Yes (Type 1)
-- Arithmetic        : fixed
-- Numerator         : s16,16 -> [-5.000000e-01 5.000000e-01)
-- Input             : s8,0 -> [-128 128)
-- Filter Internals  : Full Precision
--   Output          : s25,16 -> [-256 256)  (auto determined)
--   Product         : s23,16 -> [-64 64)  (auto determined)
--   Accumulator     : s25,16 -> [-256 256)  (auto determined)
--   Round Mode      : No rounding
--   Overflow Mode   : No overflow
-- -------------------------------------------------------------



LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.ALL;

ENTITY Hlp2 IS
   PORT( clk                             :   IN    std_logic; 
         clk_enable                      :   IN    std_logic; 
         reset                           :   IN    std_logic; 
         filter_in                       :   IN    std_logic_vector(7 DOWNTO 0); -- sfix8
         filter_out                      :   OUT   std_logic_vector(24 DOWNTO 0)  -- sfix25_En16
         );

END Hlp2;


----------------------------------------------------------------
--Module Architecture: Hlp2
----------------------------------------------------------------
ARCHITECTURE rtl OF Hlp2 IS
  -- Local Functions
  -- Type Definitions
  TYPE delay_pipeline_type IS ARRAY (NATURAL range <>) OF signed(7 DOWNTO 0); -- sfix8
  -- Constants
  CONSTANT coeff1                         : signed(15 DOWNTO 0) := to_signed(-159, 16); -- sfix16_En16
  CONSTANT coeff2                         : signed(15 DOWNTO 0) := to_signed(-137, 16); -- sfix16_En16
  CONSTANT coeff3                         : signed(15 DOWNTO 0) := to_signed(444, 16); -- sfix16_En16
  CONSTANT coeff4                         : signed(15 DOWNTO 0) := to_signed(1097, 16); -- sfix16_En16
  CONSTANT coeff5                         : signed(15 DOWNTO 0) := to_signed(729, 16); -- sfix16_En16
  CONSTANT coeff6                         : signed(15 DOWNTO 0) := to_signed(-408, 16); -- sfix16_En16
  CONSTANT coeff7                         : signed(15 DOWNTO 0) := to_signed(-551, 16); -- sfix16_En16
  CONSTANT coeff8                         : signed(15 DOWNTO 0) := to_signed(607, 16); -- sfix16_En16
  CONSTANT coeff9                         : signed(15 DOWNTO 0) := to_signed(851, 16); -- sfix16_En16
  CONSTANT coeff10                        : signed(15 DOWNTO 0) := to_signed(-663, 16); -- sfix16_En16
  CONSTANT coeff11                        : signed(15 DOWNTO 0) := to_signed(-1198, 16); -- sfix16_En16
  CONSTANT coeff12                        : signed(15 DOWNTO 0) := to_signed(749, 16); -- sfix16_En16
  CONSTANT coeff13                        : signed(15 DOWNTO 0) := to_signed(1715, 16); -- sfix16_En16
  CONSTANT coeff14                        : signed(15 DOWNTO 0) := to_signed(-818, 16); -- sfix16_En16
  CONSTANT coeff15                        : signed(15 DOWNTO 0) := to_signed(-2490, 16); -- sfix16_En16
  CONSTANT coeff16                        : signed(15 DOWNTO 0) := to_signed(877, 16); -- sfix16_En16
  CONSTANT coeff17                        : signed(15 DOWNTO 0) := to_signed(3811, 16); -- sfix16_En16
  CONSTANT coeff18                        : signed(15 DOWNTO 0) := to_signed(-921, 16); -- sfix16_En16
  CONSTANT coeff19                        : signed(15 DOWNTO 0) := to_signed(-6732, 16); -- sfix16_En16
  CONSTANT coeff20                        : signed(15 DOWNTO 0) := to_signed(948, 16); -- sfix16_En16
  CONSTANT coeff21                        : signed(15 DOWNTO 0) := to_signed(20786, 16); -- sfix16_En16
  CONSTANT coeff22                        : signed(15 DOWNTO 0) := to_signed(31810, 16); -- sfix16_En16
  CONSTANT coeff23                        : signed(15 DOWNTO 0) := to_signed(20786, 16); -- sfix16_En16
  CONSTANT coeff24                        : signed(15 DOWNTO 0) := to_signed(948, 16); -- sfix16_En16
  CONSTANT coeff25                        : signed(15 DOWNTO 0) := to_signed(-6732, 16); -- sfix16_En16
  CONSTANT coeff26                        : signed(15 DOWNTO 0) := to_signed(-921, 16); -- sfix16_En16
  CONSTANT coeff27                        : signed(15 DOWNTO 0) := to_signed(3811, 16); -- sfix16_En16
  CONSTANT coeff28                        : signed(15 DOWNTO 0) := to_signed(877, 16); -- sfix16_En16
  CONSTANT coeff29                        : signed(15 DOWNTO 0) := to_signed(-2490, 16); -- sfix16_En16
  CONSTANT coeff30                        : signed(15 DOWNTO 0) := to_signed(-818, 16); -- sfix16_En16
  CONSTANT coeff31                        : signed(15 DOWNTO 0) := to_signed(1715, 16); -- sfix16_En16
  CONSTANT coeff32                        : signed(15 DOWNTO 0) := to_signed(749, 16); -- sfix16_En16
  CONSTANT coeff33                        : signed(15 DOWNTO 0) := to_signed(-1198, 16); -- sfix16_En16
  CONSTANT coeff34                        : signed(15 DOWNTO 0) := to_signed(-663, 16); -- sfix16_En16
  CONSTANT coeff35                        : signed(15 DOWNTO 0) := to_signed(851, 16); -- sfix16_En16
  CONSTANT coeff36                        : signed(15 DOWNTO 0) := to_signed(607, 16); -- sfix16_En16
  CONSTANT coeff37                        : signed(15 DOWNTO 0) := to_signed(-551, 16); -- sfix16_En16
  CONSTANT coeff38                        : signed(15 DOWNTO 0) := to_signed(-408, 16); -- sfix16_En16
  CONSTANT coeff39                        : signed(15 DOWNTO 0) := to_signed(729, 16); -- sfix16_En16
  CONSTANT coeff40                        : signed(15 DOWNTO 0) := to_signed(1097, 16); -- sfix16_En16
  CONSTANT coeff41                        : signed(15 DOWNTO 0) := to_signed(444, 16); -- sfix16_En16
  CONSTANT coeff42                        : signed(15 DOWNTO 0) := to_signed(-137, 16); -- sfix16_En16
  CONSTANT coeff43                        : signed(15 DOWNTO 0) := to_signed(-159, 16); -- sfix16_En16

  -- Signals
  SIGNAL delay_pipeline                   : delay_pipeline_type(0 TO 42); -- sfix8
  SIGNAL product43                        : signed(22 DOWNTO 0); -- sfix23_En16
  SIGNAL mul_temp                         : signed(23 DOWNTO 0); -- sfix24_En16
  SIGNAL product42                        : signed(22 DOWNTO 0); -- sfix23_En16
  SIGNAL mul_temp_1                       : signed(23 DOWNTO 0); -- sfix24_En16
  SIGNAL product41                        : signed(22 DOWNTO 0); -- sfix23_En16
  SIGNAL mul_temp_2                       : signed(23 DOWNTO 0); -- sfix24_En16
  SIGNAL product40                        : signed(22 DOWNTO 0); -- sfix23_En16
  SIGNAL mul_temp_3                       : signed(23 DOWNTO 0); -- sfix24_En16
  SIGNAL product39                        : signed(22 DOWNTO 0); -- sfix23_En16
  SIGNAL mul_temp_4                       : signed(23 DOWNTO 0); -- sfix24_En16
  SIGNAL product38                        : signed(22 DOWNTO 0); -- sfix23_En16
  SIGNAL mul_temp_5                       : signed(23 DOWNTO 0); -- sfix24_En16
  SIGNAL product37                        : signed(22 DOWNTO 0); -- sfix23_En16
  SIGNAL mul_temp_6                       : signed(23 DOWNTO 0); -- sfix24_En16
  SIGNAL product36                        : signed(22 DOWNTO 0); -- sfix23_En16
  SIGNAL mul_temp_7                       : signed(23 DOWNTO 0); -- sfix24_En16
  SIGNAL product35                        : signed(22 DOWNTO 0); -- sfix23_En16
  SIGNAL mul_temp_8                       : signed(23 DOWNTO 0); -- sfix24_En16
  SIGNAL product34                        : signed(22 DOWNTO 0); -- sfix23_En16
  SIGNAL mul_temp_9                       : signed(23 DOWNTO 0); -- sfix24_En16
  SIGNAL product33                        : signed(22 DOWNTO 0); -- sfix23_En16
  SIGNAL mul_temp_10                      : signed(23 DOWNTO 0); -- sfix24_En16
  SIGNAL product32                        : signed(22 DOWNTO 0); -- sfix23_En16
  SIGNAL mul_temp_11                      : signed(23 DOWNTO 0); -- sfix24_En16
  SIGNAL product31                        : signed(22 DOWNTO 0); -- sfix23_En16
  SIGNAL mul_temp_12                      : signed(23 DOWNTO 0); -- sfix24_En16
  SIGNAL product30                        : signed(22 DOWNTO 0); -- sfix23_En16
  SIGNAL mul_temp_13                      : signed(23 DOWNTO 0); -- sfix24_En16
  SIGNAL product29                        : signed(22 DOWNTO 0); -- sfix23_En16
  SIGNAL mul_temp_14                      : signed(23 DOWNTO 0); -- sfix24_En16
  SIGNAL product28                        : signed(22 DOWNTO 0); -- sfix23_En16
  SIGNAL mul_temp_15                      : signed(23 DOWNTO 0); -- sfix24_En16
  SIGNAL product27                        : signed(22 DOWNTO 0); -- sfix23_En16
  SIGNAL mul_temp_16                      : signed(23 DOWNTO 0); -- sfix24_En16
  SIGNAL product26                        : signed(22 DOWNTO 0); -- sfix23_En16
  SIGNAL mul_temp_17                      : signed(23 DOWNTO 0); -- sfix24_En16
  SIGNAL product25                        : signed(22 DOWNTO 0); -- sfix23_En16
  SIGNAL mul_temp_18                      : signed(23 DOWNTO 0); -- sfix24_En16
  SIGNAL product24                        : signed(22 DOWNTO 0); -- sfix23_En16
  SIGNAL mul_temp_19                      : signed(23 DOWNTO 0); -- sfix24_En16
  SIGNAL product23                        : signed(22 DOWNTO 0); -- sfix23_En16
  SIGNAL mul_temp_20                      : signed(23 DOWNTO 0); -- sfix24_En16
  SIGNAL product22                        : signed(22 DOWNTO 0); -- sfix23_En16
  SIGNAL mul_temp_21                      : signed(23 DOWNTO 0); -- sfix24_En16
  SIGNAL product21                        : signed(22 DOWNTO 0); -- sfix23_En16
  SIGNAL mul_temp_22                      : signed(23 DOWNTO 0); -- sfix24_En16
  SIGNAL product20                        : signed(22 DOWNTO 0); -- sfix23_En16
  SIGNAL mul_temp_23                      : signed(23 DOWNTO 0); -- sfix24_En16
  SIGNAL product19                        : signed(22 DOWNTO 0); -- sfix23_En16
  SIGNAL mul_temp_24                      : signed(23 DOWNTO 0); -- sfix24_En16
  SIGNAL product18                        : signed(22 DOWNTO 0); -- sfix23_En16
  SIGNAL mul_temp_25                      : signed(23 DOWNTO 0); -- sfix24_En16
  SIGNAL product17                        : signed(22 DOWNTO 0); -- sfix23_En16
  SIGNAL mul_temp_26                      : signed(23 DOWNTO 0); -- sfix24_En16
  SIGNAL product16                        : signed(22 DOWNTO 0); -- sfix23_En16
  SIGNAL mul_temp_27                      : signed(23 DOWNTO 0); -- sfix24_En16
  SIGNAL product15                        : signed(22 DOWNTO 0); -- sfix23_En16
  SIGNAL mul_temp_28                      : signed(23 DOWNTO 0); -- sfix24_En16
  SIGNAL product14                        : signed(22 DOWNTO 0); -- sfix23_En16
  SIGNAL mul_temp_29                      : signed(23 DOWNTO 0); -- sfix24_En16
  SIGNAL product13                        : signed(22 DOWNTO 0); -- sfix23_En16
  SIGNAL mul_temp_30                      : signed(23 DOWNTO 0); -- sfix24_En16
  SIGNAL product12                        : signed(22 DOWNTO 0); -- sfix23_En16
  SIGNAL mul_temp_31                      : signed(23 DOWNTO 0); -- sfix24_En16
  SIGNAL product11                        : signed(22 DOWNTO 0); -- sfix23_En16
  SIGNAL mul_temp_32                      : signed(23 DOWNTO 0); -- sfix24_En16
  SIGNAL product10                        : signed(22 DOWNTO 0); -- sfix23_En16
  SIGNAL mul_temp_33                      : signed(23 DOWNTO 0); -- sfix24_En16
  SIGNAL product9                         : signed(22 DOWNTO 0); -- sfix23_En16
  SIGNAL mul_temp_34                      : signed(23 DOWNTO 0); -- sfix24_En16
  SIGNAL product8                         : signed(22 DOWNTO 0); -- sfix23_En16
  SIGNAL mul_temp_35                      : signed(23 DOWNTO 0); -- sfix24_En16
  SIGNAL product7                         : signed(22 DOWNTO 0); -- sfix23_En16
  SIGNAL mul_temp_36                      : signed(23 DOWNTO 0); -- sfix24_En16
  SIGNAL product6                         : signed(22 DOWNTO 0); -- sfix23_En16
  SIGNAL mul_temp_37                      : signed(23 DOWNTO 0); -- sfix24_En16
  SIGNAL product5                         : signed(22 DOWNTO 0); -- sfix23_En16
  SIGNAL mul_temp_38                      : signed(23 DOWNTO 0); -- sfix24_En16
  SIGNAL product4                         : signed(22 DOWNTO 0); -- sfix23_En16
  SIGNAL mul_temp_39                      : signed(23 DOWNTO 0); -- sfix24_En16
  SIGNAL product3                         : signed(22 DOWNTO 0); -- sfix23_En16
  SIGNAL mul_temp_40                      : signed(23 DOWNTO 0); -- sfix24_En16
  SIGNAL product2                         : signed(22 DOWNTO 0); -- sfix23_En16
  SIGNAL mul_temp_41                      : signed(23 DOWNTO 0); -- sfix24_En16
  SIGNAL product1_cast                    : signed(24 DOWNTO 0); -- sfix25_En16
  SIGNAL product1                         : signed(22 DOWNTO 0); -- sfix23_En16
  SIGNAL mul_temp_42                      : signed(23 DOWNTO 0); -- sfix24_En16
  SIGNAL sum1                             : signed(24 DOWNTO 0); -- sfix25_En16
  SIGNAL add_temp                         : signed(25 DOWNTO 0); -- sfix26_En16
  SIGNAL sum2                             : signed(24 DOWNTO 0); -- sfix25_En16
  SIGNAL add_temp_1                       : signed(25 DOWNTO 0); -- sfix26_En16
  SIGNAL sum3                             : signed(24 DOWNTO 0); -- sfix25_En16
  SIGNAL add_temp_2                       : signed(25 DOWNTO 0); -- sfix26_En16
  SIGNAL sum4                             : signed(24 DOWNTO 0); -- sfix25_En16
  SIGNAL add_temp_3                       : signed(25 DOWNTO 0); -- sfix26_En16
  SIGNAL sum5                             : signed(24 DOWNTO 0); -- sfix25_En16
  SIGNAL add_temp_4                       : signed(25 DOWNTO 0); -- sfix26_En16
  SIGNAL sum6                             : signed(24 DOWNTO 0); -- sfix25_En16
  SIGNAL add_temp_5                       : signed(25 DOWNTO 0); -- sfix26_En16
  SIGNAL sum7                             : signed(24 DOWNTO 0); -- sfix25_En16
  SIGNAL add_temp_6                       : signed(25 DOWNTO 0); -- sfix26_En16
  SIGNAL sum8                             : signed(24 DOWNTO 0); -- sfix25_En16
  SIGNAL add_temp_7                       : signed(25 DOWNTO 0); -- sfix26_En16
  SIGNAL sum9                             : signed(24 DOWNTO 0); -- sfix25_En16
  SIGNAL add_temp_8                       : signed(25 DOWNTO 0); -- sfix26_En16
  SIGNAL sum10                            : signed(24 DOWNTO 0); -- sfix25_En16
  SIGNAL add_temp_9                       : signed(25 DOWNTO 0); -- sfix26_En16
  SIGNAL sum11                            : signed(24 DOWNTO 0); -- sfix25_En16
  SIGNAL add_temp_10                      : signed(25 DOWNTO 0); -- sfix26_En16
  SIGNAL sum12                            : signed(24 DOWNTO 0); -- sfix25_En16
  SIGNAL add_temp_11                      : signed(25 DOWNTO 0); -- sfix26_En16
  SIGNAL sum13                            : signed(24 DOWNTO 0); -- sfix25_En16
  SIGNAL add_temp_12                      : signed(25 DOWNTO 0); -- sfix26_En16
  SIGNAL sum14                            : signed(24 DOWNTO 0); -- sfix25_En16
  SIGNAL add_temp_13                      : signed(25 DOWNTO 0); -- sfix26_En16
  SIGNAL sum15                            : signed(24 DOWNTO 0); -- sfix25_En16
  SIGNAL add_temp_14                      : signed(25 DOWNTO 0); -- sfix26_En16
  SIGNAL sum16                            : signed(24 DOWNTO 0); -- sfix25_En16
  SIGNAL add_temp_15                      : signed(25 DOWNTO 0); -- sfix26_En16
  SIGNAL sum17                            : signed(24 DOWNTO 0); -- sfix25_En16
  SIGNAL add_temp_16                      : signed(25 DOWNTO 0); -- sfix26_En16
  SIGNAL sum18                            : signed(24 DOWNTO 0); -- sfix25_En16
  SIGNAL add_temp_17                      : signed(25 DOWNTO 0); -- sfix26_En16
  SIGNAL sum19                            : signed(24 DOWNTO 0); -- sfix25_En16
  SIGNAL add_temp_18                      : signed(25 DOWNTO 0); -- sfix26_En16
  SIGNAL sum20                            : signed(24 DOWNTO 0); -- sfix25_En16
  SIGNAL add_temp_19                      : signed(25 DOWNTO 0); -- sfix26_En16
  SIGNAL sum21                            : signed(24 DOWNTO 0); -- sfix25_En16
  SIGNAL add_temp_20                      : signed(25 DOWNTO 0); -- sfix26_En16
  SIGNAL sum22                            : signed(24 DOWNTO 0); -- sfix25_En16
  SIGNAL add_temp_21                      : signed(25 DOWNTO 0); -- sfix26_En16
  SIGNAL sum23                            : signed(24 DOWNTO 0); -- sfix25_En16
  SIGNAL add_temp_22                      : signed(25 DOWNTO 0); -- sfix26_En16
  SIGNAL sum24                            : signed(24 DOWNTO 0); -- sfix25_En16
  SIGNAL add_temp_23                      : signed(25 DOWNTO 0); -- sfix26_En16
  SIGNAL sum25                            : signed(24 DOWNTO 0); -- sfix25_En16
  SIGNAL add_temp_24                      : signed(25 DOWNTO 0); -- sfix26_En16
  SIGNAL sum26                            : signed(24 DOWNTO 0); -- sfix25_En16
  SIGNAL add_temp_25                      : signed(25 DOWNTO 0); -- sfix26_En16
  SIGNAL sum27                            : signed(24 DOWNTO 0); -- sfix25_En16
  SIGNAL add_temp_26                      : signed(25 DOWNTO 0); -- sfix26_En16
  SIGNAL sum28                            : signed(24 DOWNTO 0); -- sfix25_En16
  SIGNAL add_temp_27                      : signed(25 DOWNTO 0); -- sfix26_En16
  SIGNAL sum29                            : signed(24 DOWNTO 0); -- sfix25_En16
  SIGNAL add_temp_28                      : signed(25 DOWNTO 0); -- sfix26_En16
  SIGNAL sum30                            : signed(24 DOWNTO 0); -- sfix25_En16
  SIGNAL add_temp_29                      : signed(25 DOWNTO 0); -- sfix26_En16
  SIGNAL sum31                            : signed(24 DOWNTO 0); -- sfix25_En16
  SIGNAL add_temp_30                      : signed(25 DOWNTO 0); -- sfix26_En16
  SIGNAL sum32                            : signed(24 DOWNTO 0); -- sfix25_En16
  SIGNAL add_temp_31                      : signed(25 DOWNTO 0); -- sfix26_En16
  SIGNAL sum33                            : signed(24 DOWNTO 0); -- sfix25_En16
  SIGNAL add_temp_32                      : signed(25 DOWNTO 0); -- sfix26_En16
  SIGNAL sum34                            : signed(24 DOWNTO 0); -- sfix25_En16
  SIGNAL add_temp_33                      : signed(25 DOWNTO 0); -- sfix26_En16
  SIGNAL sum35                            : signed(24 DOWNTO 0); -- sfix25_En16
  SIGNAL add_temp_34                      : signed(25 DOWNTO 0); -- sfix26_En16
  SIGNAL sum36                            : signed(24 DOWNTO 0); -- sfix25_En16
  SIGNAL add_temp_35                      : signed(25 DOWNTO 0); -- sfix26_En16
  SIGNAL sum37                            : signed(24 DOWNTO 0); -- sfix25_En16
  SIGNAL add_temp_36                      : signed(25 DOWNTO 0); -- sfix26_En16
  SIGNAL sum38                            : signed(24 DOWNTO 0); -- sfix25_En16
  SIGNAL add_temp_37                      : signed(25 DOWNTO 0); -- sfix26_En16
  SIGNAL sum39                            : signed(24 DOWNTO 0); -- sfix25_En16
  SIGNAL add_temp_38                      : signed(25 DOWNTO 0); -- sfix26_En16
  SIGNAL sum40                            : signed(24 DOWNTO 0); -- sfix25_En16
  SIGNAL add_temp_39                      : signed(25 DOWNTO 0); -- sfix26_En16
  SIGNAL sum41                            : signed(24 DOWNTO 0); -- sfix25_En16
  SIGNAL add_temp_40                      : signed(25 DOWNTO 0); -- sfix26_En16
  SIGNAL sum42                            : signed(24 DOWNTO 0); -- sfix25_En16
  SIGNAL add_temp_41                      : signed(25 DOWNTO 0); -- sfix26_En16
  SIGNAL output_typeconvert               : signed(24 DOWNTO 0); -- sfix25_En16
  SIGNAL output_register                  : signed(24 DOWNTO 0); -- sfix25_En16


BEGIN

  -- Block Statements
  Delay_Pipeline_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_pipeline(0 TO 42) <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_pipeline(0) <= signed(filter_in);
        delay_pipeline(1 TO 42) <= delay_pipeline(0 TO 41);
      END IF;
    END IF; 
  END PROCESS Delay_Pipeline_process;

  mul_temp <= delay_pipeline(42) * coeff43;
  product43 <= mul_temp(22 DOWNTO 0);

  mul_temp_1 <= delay_pipeline(41) * coeff42;
  product42 <= mul_temp_1(22 DOWNTO 0);

  mul_temp_2 <= delay_pipeline(40) * coeff41;
  product41 <= mul_temp_2(22 DOWNTO 0);

  mul_temp_3 <= delay_pipeline(39) * coeff40;
  product40 <= mul_temp_3(22 DOWNTO 0);

  mul_temp_4 <= delay_pipeline(38) * coeff39;
  product39 <= mul_temp_4(22 DOWNTO 0);

  mul_temp_5 <= delay_pipeline(37) * coeff38;
  product38 <= mul_temp_5(22 DOWNTO 0);

  mul_temp_6 <= delay_pipeline(36) * coeff37;
  product37 <= mul_temp_6(22 DOWNTO 0);

  mul_temp_7 <= delay_pipeline(35) * coeff36;
  product36 <= mul_temp_7(22 DOWNTO 0);

  mul_temp_8 <= delay_pipeline(34) * coeff35;
  product35 <= mul_temp_8(22 DOWNTO 0);

  mul_temp_9 <= delay_pipeline(33) * coeff34;
  product34 <= mul_temp_9(22 DOWNTO 0);

  mul_temp_10 <= delay_pipeline(32) * coeff33;
  product33 <= mul_temp_10(22 DOWNTO 0);

  mul_temp_11 <= delay_pipeline(31) * coeff32;
  product32 <= mul_temp_11(22 DOWNTO 0);

  mul_temp_12 <= delay_pipeline(30) * coeff31;
  product31 <= mul_temp_12(22 DOWNTO 0);

  mul_temp_13 <= delay_pipeline(29) * coeff30;
  product30 <= mul_temp_13(22 DOWNTO 0);

  mul_temp_14 <= delay_pipeline(28) * coeff29;
  product29 <= mul_temp_14(22 DOWNTO 0);

  mul_temp_15 <= delay_pipeline(27) * coeff28;
  product28 <= mul_temp_15(22 DOWNTO 0);

  mul_temp_16 <= delay_pipeline(26) * coeff27;
  product27 <= mul_temp_16(22 DOWNTO 0);

  mul_temp_17 <= delay_pipeline(25) * coeff26;
  product26 <= mul_temp_17(22 DOWNTO 0);

  mul_temp_18 <= delay_pipeline(24) * coeff25;
  product25 <= mul_temp_18(22 DOWNTO 0);

  mul_temp_19 <= delay_pipeline(23) * coeff24;
  product24 <= mul_temp_19(22 DOWNTO 0);

  mul_temp_20 <= delay_pipeline(22) * coeff23;
  product23 <= mul_temp_20(22 DOWNTO 0);

  mul_temp_21 <= delay_pipeline(21) * coeff22;
  product22 <= mul_temp_21(22 DOWNTO 0);

  mul_temp_22 <= delay_pipeline(20) * coeff21;
  product21 <= mul_temp_22(22 DOWNTO 0);

  mul_temp_23 <= delay_pipeline(19) * coeff20;
  product20 <= mul_temp_23(22 DOWNTO 0);

  mul_temp_24 <= delay_pipeline(18) * coeff19;
  product19 <= mul_temp_24(22 DOWNTO 0);

  mul_temp_25 <= delay_pipeline(17) * coeff18;
  product18 <= mul_temp_25(22 DOWNTO 0);

  mul_temp_26 <= delay_pipeline(16) * coeff17;
  product17 <= mul_temp_26(22 DOWNTO 0);

  mul_temp_27 <= delay_pipeline(15) * coeff16;
  product16 <= mul_temp_27(22 DOWNTO 0);

  mul_temp_28 <= delay_pipeline(14) * coeff15;
  product15 <= mul_temp_28(22 DOWNTO 0);

  mul_temp_29 <= delay_pipeline(13) * coeff14;
  product14 <= mul_temp_29(22 DOWNTO 0);

  mul_temp_30 <= delay_pipeline(12) * coeff13;
  product13 <= mul_temp_30(22 DOWNTO 0);

  mul_temp_31 <= delay_pipeline(11) * coeff12;
  product12 <= mul_temp_31(22 DOWNTO 0);

  mul_temp_32 <= delay_pipeline(10) * coeff11;
  product11 <= mul_temp_32(22 DOWNTO 0);

  mul_temp_33 <= delay_pipeline(9) * coeff10;
  product10 <= mul_temp_33(22 DOWNTO 0);

  mul_temp_34 <= delay_pipeline(8) * coeff9;
  product9 <= mul_temp_34(22 DOWNTO 0);

  mul_temp_35 <= delay_pipeline(7) * coeff8;
  product8 <= mul_temp_35(22 DOWNTO 0);

  mul_temp_36 <= delay_pipeline(6) * coeff7;
  product7 <= mul_temp_36(22 DOWNTO 0);

  mul_temp_37 <= delay_pipeline(5) * coeff6;
  product6 <= mul_temp_37(22 DOWNTO 0);

  mul_temp_38 <= delay_pipeline(4) * coeff5;
  product5 <= mul_temp_38(22 DOWNTO 0);

  mul_temp_39 <= delay_pipeline(3) * coeff4;
  product4 <= mul_temp_39(22 DOWNTO 0);

  mul_temp_40 <= delay_pipeline(2) * coeff3;
  product3 <= mul_temp_40(22 DOWNTO 0);

  mul_temp_41 <= delay_pipeline(1) * coeff2;
  product2 <= mul_temp_41(22 DOWNTO 0);

  product1_cast <= resize(product1, 25);

  mul_temp_42 <= delay_pipeline(0) * coeff1;
  product1 <= mul_temp_42(22 DOWNTO 0);

  add_temp <= resize(product1_cast, 26) + resize(product2, 26);
  sum1 <= add_temp(24 DOWNTO 0);

  add_temp_1 <= resize(sum1, 26) + resize(product3, 26);
  sum2 <= add_temp_1(24 DOWNTO 0);

  add_temp_2 <= resize(sum2, 26) + resize(product4, 26);
  sum3 <= add_temp_2(24 DOWNTO 0);

  add_temp_3 <= resize(sum3, 26) + resize(product5, 26);
  sum4 <= add_temp_3(24 DOWNTO 0);

  add_temp_4 <= resize(sum4, 26) + resize(product6, 26);
  sum5 <= add_temp_4(24 DOWNTO 0);

  add_temp_5 <= resize(sum5, 26) + resize(product7, 26);
  sum6 <= add_temp_5(24 DOWNTO 0);

  add_temp_6 <= resize(sum6, 26) + resize(product8, 26);
  sum7 <= add_temp_6(24 DOWNTO 0);

  add_temp_7 <= resize(sum7, 26) + resize(product9, 26);
  sum8 <= add_temp_7(24 DOWNTO 0);

  add_temp_8 <= resize(sum8, 26) + resize(product10, 26);
  sum9 <= add_temp_8(24 DOWNTO 0);

  add_temp_9 <= resize(sum9, 26) + resize(product11, 26);
  sum10 <= add_temp_9(24 DOWNTO 0);

  add_temp_10 <= resize(sum10, 26) + resize(product12, 26);
  sum11 <= add_temp_10(24 DOWNTO 0);

  add_temp_11 <= resize(sum11, 26) + resize(product13, 26);
  sum12 <= add_temp_11(24 DOWNTO 0);

  add_temp_12 <= resize(sum12, 26) + resize(product14, 26);
  sum13 <= add_temp_12(24 DOWNTO 0);

  add_temp_13 <= resize(sum13, 26) + resize(product15, 26);
  sum14 <= add_temp_13(24 DOWNTO 0);

  add_temp_14 <= resize(sum14, 26) + resize(product16, 26);
  sum15 <= add_temp_14(24 DOWNTO 0);

  add_temp_15 <= resize(sum15, 26) + resize(product17, 26);
  sum16 <= add_temp_15(24 DOWNTO 0);

  add_temp_16 <= resize(sum16, 26) + resize(product18, 26);
  sum17 <= add_temp_16(24 DOWNTO 0);

  add_temp_17 <= resize(sum17, 26) + resize(product19, 26);
  sum18 <= add_temp_17(24 DOWNTO 0);

  add_temp_18 <= resize(sum18, 26) + resize(product20, 26);
  sum19 <= add_temp_18(24 DOWNTO 0);

  add_temp_19 <= resize(sum19, 26) + resize(product21, 26);
  sum20 <= add_temp_19(24 DOWNTO 0);

  add_temp_20 <= resize(sum20, 26) + resize(product22, 26);
  sum21 <= add_temp_20(24 DOWNTO 0);

  add_temp_21 <= resize(sum21, 26) + resize(product23, 26);
  sum22 <= add_temp_21(24 DOWNTO 0);

  add_temp_22 <= resize(sum22, 26) + resize(product24, 26);
  sum23 <= add_temp_22(24 DOWNTO 0);

  add_temp_23 <= resize(sum23, 26) + resize(product25, 26);
  sum24 <= add_temp_23(24 DOWNTO 0);

  add_temp_24 <= resize(sum24, 26) + resize(product26, 26);
  sum25 <= add_temp_24(24 DOWNTO 0);

  add_temp_25 <= resize(sum25, 26) + resize(product27, 26);
  sum26 <= add_temp_25(24 DOWNTO 0);

  add_temp_26 <= resize(sum26, 26) + resize(product28, 26);
  sum27 <= add_temp_26(24 DOWNTO 0);

  add_temp_27 <= resize(sum27, 26) + resize(product29, 26);
  sum28 <= add_temp_27(24 DOWNTO 0);

  add_temp_28 <= resize(sum28, 26) + resize(product30, 26);
  sum29 <= add_temp_28(24 DOWNTO 0);

  add_temp_29 <= resize(sum29, 26) + resize(product31, 26);
  sum30 <= add_temp_29(24 DOWNTO 0);

  add_temp_30 <= resize(sum30, 26) + resize(product32, 26);
  sum31 <= add_temp_30(24 DOWNTO 0);

  add_temp_31 <= resize(sum31, 26) + resize(product33, 26);
  sum32 <= add_temp_31(24 DOWNTO 0);

  add_temp_32 <= resize(sum32, 26) + resize(product34, 26);
  sum33 <= add_temp_32(24 DOWNTO 0);

  add_temp_33 <= resize(sum33, 26) + resize(product35, 26);
  sum34 <= add_temp_33(24 DOWNTO 0);

  add_temp_34 <= resize(sum34, 26) + resize(product36, 26);
  sum35 <= add_temp_34(24 DOWNTO 0);

  add_temp_35 <= resize(sum35, 26) + resize(product37, 26);
  sum36 <= add_temp_35(24 DOWNTO 0);

  add_temp_36 <= resize(sum36, 26) + resize(product38, 26);
  sum37 <= add_temp_36(24 DOWNTO 0);

  add_temp_37 <= resize(sum37, 26) + resize(product39, 26);
  sum38 <= add_temp_37(24 DOWNTO 0);

  add_temp_38 <= resize(sum38, 26) + resize(product40, 26);
  sum39 <= add_temp_38(24 DOWNTO 0);

  add_temp_39 <= resize(sum39, 26) + resize(product41, 26);
  sum40 <= add_temp_39(24 DOWNTO 0);

  add_temp_40 <= resize(sum40, 26) + resize(product42, 26);
  sum41 <= add_temp_40(24 DOWNTO 0);

  add_temp_41 <= resize(sum41, 26) + resize(product43, 26);
  sum42 <= add_temp_41(24 DOWNTO 0);

  output_typeconvert <= sum42;

  Output_Register_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      output_register <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        output_register <= output_typeconvert;
      END IF;
    END IF; 
  END PROCESS Output_Register_process;

  -- Assignment Statements
  filter_out <= std_logic_vector(output_register);
END rtl;
