// -------------------------------------------------------------
//
// Module: lowPassFir
// Generated by MATLAB(R) 23.2 and Filter Design HDL Coder 23.2.
// Generated on: 2023-11-29 19:55:54
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Code Generation Options:
//
// Name: lowPassFir
// TargetLanguage: Verilog
// TestBenchName: Hlp2_tb
// TestBenchStimulus: impulse step ramp chirp noise 
// LoopUnrolling: on

// Filter Specifications:
//
// Sample Rate     : N/A (normalized frequency)
// Response        : Lowpass
// Specification   : Fp,Fst,Ap,Ast
// Passband Ripple : 1 dB
// Stopband Edge   : 0.55
// Stopband Atten. : 60 dB
// Passband Edge   : 0.45
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Implementation    : Fully parallel
// Folding Factor        : 1
// -------------------------------------------------------------
// Filter Settings:
//
// Discrete-Time FIR Filter (real)
// -------------------------------
// Filter Structure  : Direct-Form FIR
// Filter Length     : 43
// Stable            : Yes
// Linear Phase      : Yes (Type 1)
// Arithmetic        : fixed
// Numerator         : s16,16 -> [-5.000000e-01 5.000000e-01)
// Input             : s8,0 -> [-128 128)
// Filter Internals  : Full Precision
//   Output          : s25,16 -> [-256 256)  (auto determined)
//   Product         : s23,16 -> [-64 64)  (auto determined)
//   Accumulator     : s25,16 -> [-256 256)  (auto determined)
//   Round Mode      : No rounding
//   Overflow Mode   : No overflow
// -------------------------------------------------------------




`timescale 1 ns / 1 ns

module lowPassFir
               (
                clk,
                clk_enable,
                reset,
                filter_in,
                filter_out
                );

  input   clk; 
  input   clk_enable; 
  input   reset; 
  input   signed [7:0] filter_in; //sfix8
  output  signed [24:0] filter_out; //sfix25_En16

////////////////////////////////////////////////////////////////
//Module Architecture: lowPassFir
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants
  parameter signed [15:0] coeff1 = 16'b1111111101100001; //sfix16_En16
  parameter signed [15:0] coeff2 = 16'b1111111101110111; //sfix16_En16
  parameter signed [15:0] coeff3 = 16'b0000000110111100; //sfix16_En16
  parameter signed [15:0] coeff4 = 16'b0000010001001001; //sfix16_En16
  parameter signed [15:0] coeff5 = 16'b0000001011011001; //sfix16_En16
  parameter signed [15:0] coeff6 = 16'b1111111001101000; //sfix16_En16
  parameter signed [15:0] coeff7 = 16'b1111110111011001; //sfix16_En16
  parameter signed [15:0] coeff8 = 16'b0000001001011111; //sfix16_En16
  parameter signed [15:0] coeff9 = 16'b0000001101010011; //sfix16_En16
  parameter signed [15:0] coeff10 = 16'b1111110101101001; //sfix16_En16
  parameter signed [15:0] coeff11 = 16'b1111101101010010; //sfix16_En16
  parameter signed [15:0] coeff12 = 16'b0000001011101101; //sfix16_En16
  parameter signed [15:0] coeff13 = 16'b0000011010110011; //sfix16_En16
  parameter signed [15:0] coeff14 = 16'b1111110011001110; //sfix16_En16
  parameter signed [15:0] coeff15 = 16'b1111011001000110; //sfix16_En16
  parameter signed [15:0] coeff16 = 16'b0000001101101101; //sfix16_En16
  parameter signed [15:0] coeff17 = 16'b0000111011100011; //sfix16_En16
  parameter signed [15:0] coeff18 = 16'b1111110001100111; //sfix16_En16
  parameter signed [15:0] coeff19 = 16'b1110010110110100; //sfix16_En16
  parameter signed [15:0] coeff20 = 16'b0000001110110100; //sfix16_En16
  parameter signed [15:0] coeff21 = 16'b0101000100110010; //sfix16_En16
  parameter signed [15:0] coeff22 = 16'b0111110001000010; //sfix16_En16
  parameter signed [15:0] coeff23 = 16'b0101000100110010; //sfix16_En16
  parameter signed [15:0] coeff24 = 16'b0000001110110100; //sfix16_En16
  parameter signed [15:0] coeff25 = 16'b1110010110110100; //sfix16_En16
  parameter signed [15:0] coeff26 = 16'b1111110001100111; //sfix16_En16
  parameter signed [15:0] coeff27 = 16'b0000111011100011; //sfix16_En16
  parameter signed [15:0] coeff28 = 16'b0000001101101101; //sfix16_En16
  parameter signed [15:0] coeff29 = 16'b1111011001000110; //sfix16_En16
  parameter signed [15:0] coeff30 = 16'b1111110011001110; //sfix16_En16
  parameter signed [15:0] coeff31 = 16'b0000011010110011; //sfix16_En16
  parameter signed [15:0] coeff32 = 16'b0000001011101101; //sfix16_En16
  parameter signed [15:0] coeff33 = 16'b1111101101010010; //sfix16_En16
  parameter signed [15:0] coeff34 = 16'b1111110101101001; //sfix16_En16
  parameter signed [15:0] coeff35 = 16'b0000001101010011; //sfix16_En16
  parameter signed [15:0] coeff36 = 16'b0000001001011111; //sfix16_En16
  parameter signed [15:0] coeff37 = 16'b1111110111011001; //sfix16_En16
  parameter signed [15:0] coeff38 = 16'b1111111001101000; //sfix16_En16
  parameter signed [15:0] coeff39 = 16'b0000001011011001; //sfix16_En16
  parameter signed [15:0] coeff40 = 16'b0000010001001001; //sfix16_En16
  parameter signed [15:0] coeff41 = 16'b0000000110111100; //sfix16_En16
  parameter signed [15:0] coeff42 = 16'b1111111101110111; //sfix16_En16
  parameter signed [15:0] coeff43 = 16'b1111111101100001; //sfix16_En16

  // Signals
  reg  signed [7:0] delay_pipeline [0:42] ; // sfix8
  wire signed [22:0] product43; // sfix23_En16
  wire signed [23:0] mul_temp; // sfix24_En16
  wire signed [22:0] product42; // sfix23_En16
  wire signed [23:0] mul_temp_1; // sfix24_En16
  wire signed [22:0] product41; // sfix23_En16
  wire signed [23:0] mul_temp_2; // sfix24_En16
  wire signed [22:0] product40; // sfix23_En16
  wire signed [23:0] mul_temp_3; // sfix24_En16
  wire signed [22:0] product39; // sfix23_En16
  wire signed [23:0] mul_temp_4; // sfix24_En16
  wire signed [22:0] product38; // sfix23_En16
  wire signed [23:0] mul_temp_5; // sfix24_En16
  wire signed [22:0] product37; // sfix23_En16
  wire signed [23:0] mul_temp_6; // sfix24_En16
  wire signed [22:0] product36; // sfix23_En16
  wire signed [23:0] mul_temp_7; // sfix24_En16
  wire signed [22:0] product35; // sfix23_En16
  wire signed [23:0] mul_temp_8; // sfix24_En16
  wire signed [22:0] product34; // sfix23_En16
  wire signed [23:0] mul_temp_9; // sfix24_En16
  wire signed [22:0] product33; // sfix23_En16
  wire signed [23:0] mul_temp_10; // sfix24_En16
  wire signed [22:0] product32; // sfix23_En16
  wire signed [23:0] mul_temp_11; // sfix24_En16
  wire signed [22:0] product31; // sfix23_En16
  wire signed [23:0] mul_temp_12; // sfix24_En16
  wire signed [22:0] product30; // sfix23_En16
  wire signed [23:0] mul_temp_13; // sfix24_En16
  wire signed [22:0] product29; // sfix23_En16
  wire signed [23:0] mul_temp_14; // sfix24_En16
  wire signed [22:0] product28; // sfix23_En16
  wire signed [23:0] mul_temp_15; // sfix24_En16
  wire signed [22:0] product27; // sfix23_En16
  wire signed [23:0] mul_temp_16; // sfix24_En16
  wire signed [22:0] product26; // sfix23_En16
  wire signed [23:0] mul_temp_17; // sfix24_En16
  wire signed [22:0] product25; // sfix23_En16
  wire signed [23:0] mul_temp_18; // sfix24_En16
  wire signed [22:0] product24; // sfix23_En16
  wire signed [23:0] mul_temp_19; // sfix24_En16
  wire signed [22:0] product23; // sfix23_En16
  wire signed [23:0] mul_temp_20; // sfix24_En16
  wire signed [22:0] product22; // sfix23_En16
  wire signed [23:0] mul_temp_21; // sfix24_En16
  wire signed [22:0] product21; // sfix23_En16
  wire signed [23:0] mul_temp_22; // sfix24_En16
  wire signed [22:0] product20; // sfix23_En16
  wire signed [23:0] mul_temp_23; // sfix24_En16
  wire signed [22:0] product19; // sfix23_En16
  wire signed [23:0] mul_temp_24; // sfix24_En16
  wire signed [22:0] product18; // sfix23_En16
  wire signed [23:0] mul_temp_25; // sfix24_En16
  wire signed [22:0] product17; // sfix23_En16
  wire signed [23:0] mul_temp_26; // sfix24_En16
  wire signed [22:0] product16; // sfix23_En16
  wire signed [23:0] mul_temp_27; // sfix24_En16
  wire signed [22:0] product15; // sfix23_En16
  wire signed [23:0] mul_temp_28; // sfix24_En16
  wire signed [22:0] product14; // sfix23_En16
  wire signed [23:0] mul_temp_29; // sfix24_En16
  wire signed [22:0] product13; // sfix23_En16
  wire signed [23:0] mul_temp_30; // sfix24_En16
  wire signed [22:0] product12; // sfix23_En16
  wire signed [23:0] mul_temp_31; // sfix24_En16
  wire signed [22:0] product11; // sfix23_En16
  wire signed [23:0] mul_temp_32; // sfix24_En16
  wire signed [22:0] product10; // sfix23_En16
  wire signed [23:0] mul_temp_33; // sfix24_En16
  wire signed [22:0] product9; // sfix23_En16
  wire signed [23:0] mul_temp_34; // sfix24_En16
  wire signed [22:0] product8; // sfix23_En16
  wire signed [23:0] mul_temp_35; // sfix24_En16
  wire signed [22:0] product7; // sfix23_En16
  wire signed [23:0] mul_temp_36; // sfix24_En16
  wire signed [22:0] product6; // sfix23_En16
  wire signed [23:0] mul_temp_37; // sfix24_En16
  wire signed [22:0] product5; // sfix23_En16
  wire signed [23:0] mul_temp_38; // sfix24_En16
  wire signed [22:0] product4; // sfix23_En16
  wire signed [23:0] mul_temp_39; // sfix24_En16
  wire signed [22:0] product3; // sfix23_En16
  wire signed [23:0] mul_temp_40; // sfix24_En16
  wire signed [22:0] product2; // sfix23_En16
  wire signed [23:0] mul_temp_41; // sfix24_En16
  wire signed [24:0] product1_cast; // sfix25_En16
  wire signed [22:0] product1; // sfix23_En16
  wire signed [23:0] mul_temp_42; // sfix24_En16
  wire signed [24:0] sum1; // sfix25_En16
  wire signed [24:0] add_signext; // sfix25_En16
  wire signed [24:0] add_signext_1; // sfix25_En16
  wire signed [25:0] add_temp; // sfix26_En16
  wire signed [24:0] sum2; // sfix25_En16
  wire signed [24:0] add_signext_2; // sfix25_En16
  wire signed [24:0] add_signext_3; // sfix25_En16
  wire signed [25:0] add_temp_1; // sfix26_En16
  wire signed [24:0] sum3; // sfix25_En16
  wire signed [24:0] add_signext_4; // sfix25_En16
  wire signed [24:0] add_signext_5; // sfix25_En16
  wire signed [25:0] add_temp_2; // sfix26_En16
  wire signed [24:0] sum4; // sfix25_En16
  wire signed [24:0] add_signext_6; // sfix25_En16
  wire signed [24:0] add_signext_7; // sfix25_En16
  wire signed [25:0] add_temp_3; // sfix26_En16
  wire signed [24:0] sum5; // sfix25_En16
  wire signed [24:0] add_signext_8; // sfix25_En16
  wire signed [24:0] add_signext_9; // sfix25_En16
  wire signed [25:0] add_temp_4; // sfix26_En16
  wire signed [24:0] sum6; // sfix25_En16
  wire signed [24:0] add_signext_10; // sfix25_En16
  wire signed [24:0] add_signext_11; // sfix25_En16
  wire signed [25:0] add_temp_5; // sfix26_En16
  wire signed [24:0] sum7; // sfix25_En16
  wire signed [24:0] add_signext_12; // sfix25_En16
  wire signed [24:0] add_signext_13; // sfix25_En16
  wire signed [25:0] add_temp_6; // sfix26_En16
  wire signed [24:0] sum8; // sfix25_En16
  wire signed [24:0] add_signext_14; // sfix25_En16
  wire signed [24:0] add_signext_15; // sfix25_En16
  wire signed [25:0] add_temp_7; // sfix26_En16
  wire signed [24:0] sum9; // sfix25_En16
  wire signed [24:0] add_signext_16; // sfix25_En16
  wire signed [24:0] add_signext_17; // sfix25_En16
  wire signed [25:0] add_temp_8; // sfix26_En16
  wire signed [24:0] sum10; // sfix25_En16
  wire signed [24:0] add_signext_18; // sfix25_En16
  wire signed [24:0] add_signext_19; // sfix25_En16
  wire signed [25:0] add_temp_9; // sfix26_En16
  wire signed [24:0] sum11; // sfix25_En16
  wire signed [24:0] add_signext_20; // sfix25_En16
  wire signed [24:0] add_signext_21; // sfix25_En16
  wire signed [25:0] add_temp_10; // sfix26_En16
  wire signed [24:0] sum12; // sfix25_En16
  wire signed [24:0] add_signext_22; // sfix25_En16
  wire signed [24:0] add_signext_23; // sfix25_En16
  wire signed [25:0] add_temp_11; // sfix26_En16
  wire signed [24:0] sum13; // sfix25_En16
  wire signed [24:0] add_signext_24; // sfix25_En16
  wire signed [24:0] add_signext_25; // sfix25_En16
  wire signed [25:0] add_temp_12; // sfix26_En16
  wire signed [24:0] sum14; // sfix25_En16
  wire signed [24:0] add_signext_26; // sfix25_En16
  wire signed [24:0] add_signext_27; // sfix25_En16
  wire signed [25:0] add_temp_13; // sfix26_En16
  wire signed [24:0] sum15; // sfix25_En16
  wire signed [24:0] add_signext_28; // sfix25_En16
  wire signed [24:0] add_signext_29; // sfix25_En16
  wire signed [25:0] add_temp_14; // sfix26_En16
  wire signed [24:0] sum16; // sfix25_En16
  wire signed [24:0] add_signext_30; // sfix25_En16
  wire signed [24:0] add_signext_31; // sfix25_En16
  wire signed [25:0] add_temp_15; // sfix26_En16
  wire signed [24:0] sum17; // sfix25_En16
  wire signed [24:0] add_signext_32; // sfix25_En16
  wire signed [24:0] add_signext_33; // sfix25_En16
  wire signed [25:0] add_temp_16; // sfix26_En16
  wire signed [24:0] sum18; // sfix25_En16
  wire signed [24:0] add_signext_34; // sfix25_En16
  wire signed [24:0] add_signext_35; // sfix25_En16
  wire signed [25:0] add_temp_17; // sfix26_En16
  wire signed [24:0] sum19; // sfix25_En16
  wire signed [24:0] add_signext_36; // sfix25_En16
  wire signed [24:0] add_signext_37; // sfix25_En16
  wire signed [25:0] add_temp_18; // sfix26_En16
  wire signed [24:0] sum20; // sfix25_En16
  wire signed [24:0] add_signext_38; // sfix25_En16
  wire signed [24:0] add_signext_39; // sfix25_En16
  wire signed [25:0] add_temp_19; // sfix26_En16
  wire signed [24:0] sum21; // sfix25_En16
  wire signed [24:0] add_signext_40; // sfix25_En16
  wire signed [24:0] add_signext_41; // sfix25_En16
  wire signed [25:0] add_temp_20; // sfix26_En16
  wire signed [24:0] sum22; // sfix25_En16
  wire signed [24:0] add_signext_42; // sfix25_En16
  wire signed [24:0] add_signext_43; // sfix25_En16
  wire signed [25:0] add_temp_21; // sfix26_En16
  wire signed [24:0] sum23; // sfix25_En16
  wire signed [24:0] add_signext_44; // sfix25_En16
  wire signed [24:0] add_signext_45; // sfix25_En16
  wire signed [25:0] add_temp_22; // sfix26_En16
  wire signed [24:0] sum24; // sfix25_En16
  wire signed [24:0] add_signext_46; // sfix25_En16
  wire signed [24:0] add_signext_47; // sfix25_En16
  wire signed [25:0] add_temp_23; // sfix26_En16
  wire signed [24:0] sum25; // sfix25_En16
  wire signed [24:0] add_signext_48; // sfix25_En16
  wire signed [24:0] add_signext_49; // sfix25_En16
  wire signed [25:0] add_temp_24; // sfix26_En16
  wire signed [24:0] sum26; // sfix25_En16
  wire signed [24:0] add_signext_50; // sfix25_En16
  wire signed [24:0] add_signext_51; // sfix25_En16
  wire signed [25:0] add_temp_25; // sfix26_En16
  wire signed [24:0] sum27; // sfix25_En16
  wire signed [24:0] add_signext_52; // sfix25_En16
  wire signed [24:0] add_signext_53; // sfix25_En16
  wire signed [25:0] add_temp_26; // sfix26_En16
  wire signed [24:0] sum28; // sfix25_En16
  wire signed [24:0] add_signext_54; // sfix25_En16
  wire signed [24:0] add_signext_55; // sfix25_En16
  wire signed [25:0] add_temp_27; // sfix26_En16
  wire signed [24:0] sum29; // sfix25_En16
  wire signed [24:0] add_signext_56; // sfix25_En16
  wire signed [24:0] add_signext_57; // sfix25_En16
  wire signed [25:0] add_temp_28; // sfix26_En16
  wire signed [24:0] sum30; // sfix25_En16
  wire signed [24:0] add_signext_58; // sfix25_En16
  wire signed [24:0] add_signext_59; // sfix25_En16
  wire signed [25:0] add_temp_29; // sfix26_En16
  wire signed [24:0] sum31; // sfix25_En16
  wire signed [24:0] add_signext_60; // sfix25_En16
  wire signed [24:0] add_signext_61; // sfix25_En16
  wire signed [25:0] add_temp_30; // sfix26_En16
  wire signed [24:0] sum32; // sfix25_En16
  wire signed [24:0] add_signext_62; // sfix25_En16
  wire signed [24:0] add_signext_63; // sfix25_En16
  wire signed [25:0] add_temp_31; // sfix26_En16
  wire signed [24:0] sum33; // sfix25_En16
  wire signed [24:0] add_signext_64; // sfix25_En16
  wire signed [24:0] add_signext_65; // sfix25_En16
  wire signed [25:0] add_temp_32; // sfix26_En16
  wire signed [24:0] sum34; // sfix25_En16
  wire signed [24:0] add_signext_66; // sfix25_En16
  wire signed [24:0] add_signext_67; // sfix25_En16
  wire signed [25:0] add_temp_33; // sfix26_En16
  wire signed [24:0] sum35; // sfix25_En16
  wire signed [24:0] add_signext_68; // sfix25_En16
  wire signed [24:0] add_signext_69; // sfix25_En16
  wire signed [25:0] add_temp_34; // sfix26_En16
  wire signed [24:0] sum36; // sfix25_En16
  wire signed [24:0] add_signext_70; // sfix25_En16
  wire signed [24:0] add_signext_71; // sfix25_En16
  wire signed [25:0] add_temp_35; // sfix26_En16
  wire signed [24:0] sum37; // sfix25_En16
  wire signed [24:0] add_signext_72; // sfix25_En16
  wire signed [24:0] add_signext_73; // sfix25_En16
  wire signed [25:0] add_temp_36; // sfix26_En16
  wire signed [24:0] sum38; // sfix25_En16
  wire signed [24:0] add_signext_74; // sfix25_En16
  wire signed [24:0] add_signext_75; // sfix25_En16
  wire signed [25:0] add_temp_37; // sfix26_En16
  wire signed [24:0] sum39; // sfix25_En16
  wire signed [24:0] add_signext_76; // sfix25_En16
  wire signed [24:0] add_signext_77; // sfix25_En16
  wire signed [25:0] add_temp_38; // sfix26_En16
  wire signed [24:0] sum40; // sfix25_En16
  wire signed [24:0] add_signext_78; // sfix25_En16
  wire signed [24:0] add_signext_79; // sfix25_En16
  wire signed [25:0] add_temp_39; // sfix26_En16
  wire signed [24:0] sum41; // sfix25_En16
  wire signed [24:0] add_signext_80; // sfix25_En16
  wire signed [24:0] add_signext_81; // sfix25_En16
  wire signed [25:0] add_temp_40; // sfix26_En16
  wire signed [24:0] sum42; // sfix25_En16
  wire signed [24:0] add_signext_82; // sfix25_En16
  wire signed [24:0] add_signext_83; // sfix25_En16
  wire signed [25:0] add_temp_41; // sfix26_En16
  reg  signed [24:0] output_register; // sfix25_En16

  // Block Statements
  always @( posedge clk or posedge reset)
    begin: Delay_Pipeline_process
      if (reset == 1'b1) begin
        delay_pipeline[0] <= 0;
        delay_pipeline[1] <= 0;
        delay_pipeline[2] <= 0;
        delay_pipeline[3] <= 0;
        delay_pipeline[4] <= 0;
        delay_pipeline[5] <= 0;
        delay_pipeline[6] <= 0;
        delay_pipeline[7] <= 0;
        delay_pipeline[8] <= 0;
        delay_pipeline[9] <= 0;
        delay_pipeline[10] <= 0;
        delay_pipeline[11] <= 0;
        delay_pipeline[12] <= 0;
        delay_pipeline[13] <= 0;
        delay_pipeline[14] <= 0;
        delay_pipeline[15] <= 0;
        delay_pipeline[16] <= 0;
        delay_pipeline[17] <= 0;
        delay_pipeline[18] <= 0;
        delay_pipeline[19] <= 0;
        delay_pipeline[20] <= 0;
        delay_pipeline[21] <= 0;
        delay_pipeline[22] <= 0;
        delay_pipeline[23] <= 0;
        delay_pipeline[24] <= 0;
        delay_pipeline[25] <= 0;
        delay_pipeline[26] <= 0;
        delay_pipeline[27] <= 0;
        delay_pipeline[28] <= 0;
        delay_pipeline[29] <= 0;
        delay_pipeline[30] <= 0;
        delay_pipeline[31] <= 0;
        delay_pipeline[32] <= 0;
        delay_pipeline[33] <= 0;
        delay_pipeline[34] <= 0;
        delay_pipeline[35] <= 0;
        delay_pipeline[36] <= 0;
        delay_pipeline[37] <= 0;
        delay_pipeline[38] <= 0;
        delay_pipeline[39] <= 0;
        delay_pipeline[40] <= 0;
        delay_pipeline[41] <= 0;
        delay_pipeline[42] <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          delay_pipeline[0] <= filter_in;
          delay_pipeline[1] <= delay_pipeline[0];
          delay_pipeline[2] <= delay_pipeline[1];
          delay_pipeline[3] <= delay_pipeline[2];
          delay_pipeline[4] <= delay_pipeline[3];
          delay_pipeline[5] <= delay_pipeline[4];
          delay_pipeline[6] <= delay_pipeline[5];
          delay_pipeline[7] <= delay_pipeline[6];
          delay_pipeline[8] <= delay_pipeline[7];
          delay_pipeline[9] <= delay_pipeline[8];
          delay_pipeline[10] <= delay_pipeline[9];
          delay_pipeline[11] <= delay_pipeline[10];
          delay_pipeline[12] <= delay_pipeline[11];
          delay_pipeline[13] <= delay_pipeline[12];
          delay_pipeline[14] <= delay_pipeline[13];
          delay_pipeline[15] <= delay_pipeline[14];
          delay_pipeline[16] <= delay_pipeline[15];
          delay_pipeline[17] <= delay_pipeline[16];
          delay_pipeline[18] <= delay_pipeline[17];
          delay_pipeline[19] <= delay_pipeline[18];
          delay_pipeline[20] <= delay_pipeline[19];
          delay_pipeline[21] <= delay_pipeline[20];
          delay_pipeline[22] <= delay_pipeline[21];
          delay_pipeline[23] <= delay_pipeline[22];
          delay_pipeline[24] <= delay_pipeline[23];
          delay_pipeline[25] <= delay_pipeline[24];
          delay_pipeline[26] <= delay_pipeline[25];
          delay_pipeline[27] <= delay_pipeline[26];
          delay_pipeline[28] <= delay_pipeline[27];
          delay_pipeline[29] <= delay_pipeline[28];
          delay_pipeline[30] <= delay_pipeline[29];
          delay_pipeline[31] <= delay_pipeline[30];
          delay_pipeline[32] <= delay_pipeline[31];
          delay_pipeline[33] <= delay_pipeline[32];
          delay_pipeline[34] <= delay_pipeline[33];
          delay_pipeline[35] <= delay_pipeline[34];
          delay_pipeline[36] <= delay_pipeline[35];
          delay_pipeline[37] <= delay_pipeline[36];
          delay_pipeline[38] <= delay_pipeline[37];
          delay_pipeline[39] <= delay_pipeline[38];
          delay_pipeline[40] <= delay_pipeline[39];
          delay_pipeline[41] <= delay_pipeline[40];
          delay_pipeline[42] <= delay_pipeline[41];
        end
      end
    end // Delay_Pipeline_process


  assign mul_temp = delay_pipeline[42] * coeff43;
  assign product43 = mul_temp[22:0];

  assign mul_temp_1 = delay_pipeline[41] * coeff42;
  assign product42 = mul_temp_1[22:0];

  assign mul_temp_2 = delay_pipeline[40] * coeff41;
  assign product41 = mul_temp_2[22:0];

  assign mul_temp_3 = delay_pipeline[39] * coeff40;
  assign product40 = mul_temp_3[22:0];

  assign mul_temp_4 = delay_pipeline[38] * coeff39;
  assign product39 = mul_temp_4[22:0];

  assign mul_temp_5 = delay_pipeline[37] * coeff38;
  assign product38 = mul_temp_5[22:0];

  assign mul_temp_6 = delay_pipeline[36] * coeff37;
  assign product37 = mul_temp_6[22:0];

  assign mul_temp_7 = delay_pipeline[35] * coeff36;
  assign product36 = mul_temp_7[22:0];

  assign mul_temp_8 = delay_pipeline[34] * coeff35;
  assign product35 = mul_temp_8[22:0];

  assign mul_temp_9 = delay_pipeline[33] * coeff34;
  assign product34 = mul_temp_9[22:0];

  assign mul_temp_10 = delay_pipeline[32] * coeff33;
  assign product33 = mul_temp_10[22:0];

  assign mul_temp_11 = delay_pipeline[31] * coeff32;
  assign product32 = mul_temp_11[22:0];

  assign mul_temp_12 = delay_pipeline[30] * coeff31;
  assign product31 = mul_temp_12[22:0];

  assign mul_temp_13 = delay_pipeline[29] * coeff30;
  assign product30 = mul_temp_13[22:0];

  assign mul_temp_14 = delay_pipeline[28] * coeff29;
  assign product29 = mul_temp_14[22:0];

  assign mul_temp_15 = delay_pipeline[27] * coeff28;
  assign product28 = mul_temp_15[22:0];

  assign mul_temp_16 = delay_pipeline[26] * coeff27;
  assign product27 = mul_temp_16[22:0];

  assign mul_temp_17 = delay_pipeline[25] * coeff26;
  assign product26 = mul_temp_17[22:0];

  assign mul_temp_18 = delay_pipeline[24] * coeff25;
  assign product25 = mul_temp_18[22:0];

  assign mul_temp_19 = delay_pipeline[23] * coeff24;
  assign product24 = mul_temp_19[22:0];

  assign mul_temp_20 = delay_pipeline[22] * coeff23;
  assign product23 = mul_temp_20[22:0];

  assign mul_temp_21 = delay_pipeline[21] * coeff22;
  assign product22 = mul_temp_21[22:0];

  assign mul_temp_22 = delay_pipeline[20] * coeff21;
  assign product21 = mul_temp_22[22:0];

  assign mul_temp_23 = delay_pipeline[19] * coeff20;
  assign product20 = mul_temp_23[22:0];

  assign mul_temp_24 = delay_pipeline[18] * coeff19;
  assign product19 = mul_temp_24[22:0];

  assign mul_temp_25 = delay_pipeline[17] * coeff18;
  assign product18 = mul_temp_25[22:0];

  assign mul_temp_26 = delay_pipeline[16] * coeff17;
  assign product17 = mul_temp_26[22:0];

  assign mul_temp_27 = delay_pipeline[15] * coeff16;
  assign product16 = mul_temp_27[22:0];

  assign mul_temp_28 = delay_pipeline[14] * coeff15;
  assign product15 = mul_temp_28[22:0];

  assign mul_temp_29 = delay_pipeline[13] * coeff14;
  assign product14 = mul_temp_29[22:0];

  assign mul_temp_30 = delay_pipeline[12] * coeff13;
  assign product13 = mul_temp_30[22:0];

  assign mul_temp_31 = delay_pipeline[11] * coeff12;
  assign product12 = mul_temp_31[22:0];

  assign mul_temp_32 = delay_pipeline[10] * coeff11;
  assign product11 = mul_temp_32[22:0];

  assign mul_temp_33 = delay_pipeline[9] * coeff10;
  assign product10 = mul_temp_33[22:0];

  assign mul_temp_34 = delay_pipeline[8] * coeff9;
  assign product9 = mul_temp_34[22:0];

  assign mul_temp_35 = delay_pipeline[7] * coeff8;
  assign product8 = mul_temp_35[22:0];

  assign mul_temp_36 = delay_pipeline[6] * coeff7;
  assign product7 = mul_temp_36[22:0];

  assign mul_temp_37 = delay_pipeline[5] * coeff6;
  assign product6 = mul_temp_37[22:0];

  assign mul_temp_38 = delay_pipeline[4] * coeff5;
  assign product5 = mul_temp_38[22:0];

  assign mul_temp_39 = delay_pipeline[3] * coeff4;
  assign product4 = mul_temp_39[22:0];

  assign mul_temp_40 = delay_pipeline[2] * coeff3;
  assign product3 = mul_temp_40[22:0];

  assign mul_temp_41 = delay_pipeline[1] * coeff2;
  assign product2 = mul_temp_41[22:0];

  assign product1_cast = $signed({{2{product1[22]}}, product1});

  assign mul_temp_42 = delay_pipeline[0] * coeff1;
  assign product1 = mul_temp_42[22:0];

  assign add_signext = product1_cast;
  assign add_signext_1 = $signed({{2{product2[22]}}, product2});
  assign add_temp = add_signext + add_signext_1;
  assign sum1 = add_temp[24:0];

  assign add_signext_2 = sum1;
  assign add_signext_3 = $signed({{2{product3[22]}}, product3});
  assign add_temp_1 = add_signext_2 + add_signext_3;
  assign sum2 = add_temp_1[24:0];

  assign add_signext_4 = sum2;
  assign add_signext_5 = $signed({{2{product4[22]}}, product4});
  assign add_temp_2 = add_signext_4 + add_signext_5;
  assign sum3 = add_temp_2[24:0];

  assign add_signext_6 = sum3;
  assign add_signext_7 = $signed({{2{product5[22]}}, product5});
  assign add_temp_3 = add_signext_6 + add_signext_7;
  assign sum4 = add_temp_3[24:0];

  assign add_signext_8 = sum4;
  assign add_signext_9 = $signed({{2{product6[22]}}, product6});
  assign add_temp_4 = add_signext_8 + add_signext_9;
  assign sum5 = add_temp_4[24:0];

  assign add_signext_10 = sum5;
  assign add_signext_11 = $signed({{2{product7[22]}}, product7});
  assign add_temp_5 = add_signext_10 + add_signext_11;
  assign sum6 = add_temp_5[24:0];

  assign add_signext_12 = sum6;
  assign add_signext_13 = $signed({{2{product8[22]}}, product8});
  assign add_temp_6 = add_signext_12 + add_signext_13;
  assign sum7 = add_temp_6[24:0];

  assign add_signext_14 = sum7;
  assign add_signext_15 = $signed({{2{product9[22]}}, product9});
  assign add_temp_7 = add_signext_14 + add_signext_15;
  assign sum8 = add_temp_7[24:0];

  assign add_signext_16 = sum8;
  assign add_signext_17 = $signed({{2{product10[22]}}, product10});
  assign add_temp_8 = add_signext_16 + add_signext_17;
  assign sum9 = add_temp_8[24:0];

  assign add_signext_18 = sum9;
  assign add_signext_19 = $signed({{2{product11[22]}}, product11});
  assign add_temp_9 = add_signext_18 + add_signext_19;
  assign sum10 = add_temp_9[24:0];

  assign add_signext_20 = sum10;
  assign add_signext_21 = $signed({{2{product12[22]}}, product12});
  assign add_temp_10 = add_signext_20 + add_signext_21;
  assign sum11 = add_temp_10[24:0];

  assign add_signext_22 = sum11;
  assign add_signext_23 = $signed({{2{product13[22]}}, product13});
  assign add_temp_11 = add_signext_22 + add_signext_23;
  assign sum12 = add_temp_11[24:0];

  assign add_signext_24 = sum12;
  assign add_signext_25 = $signed({{2{product14[22]}}, product14});
  assign add_temp_12 = add_signext_24 + add_signext_25;
  assign sum13 = add_temp_12[24:0];

  assign add_signext_26 = sum13;
  assign add_signext_27 = $signed({{2{product15[22]}}, product15});
  assign add_temp_13 = add_signext_26 + add_signext_27;
  assign sum14 = add_temp_13[24:0];

  assign add_signext_28 = sum14;
  assign add_signext_29 = $signed({{2{product16[22]}}, product16});
  assign add_temp_14 = add_signext_28 + add_signext_29;
  assign sum15 = add_temp_14[24:0];

  assign add_signext_30 = sum15;
  assign add_signext_31 = $signed({{2{product17[22]}}, product17});
  assign add_temp_15 = add_signext_30 + add_signext_31;
  assign sum16 = add_temp_15[24:0];

  assign add_signext_32 = sum16;
  assign add_signext_33 = $signed({{2{product18[22]}}, product18});
  assign add_temp_16 = add_signext_32 + add_signext_33;
  assign sum17 = add_temp_16[24:0];

  assign add_signext_34 = sum17;
  assign add_signext_35 = $signed({{2{product19[22]}}, product19});
  assign add_temp_17 = add_signext_34 + add_signext_35;
  assign sum18 = add_temp_17[24:0];

  assign add_signext_36 = sum18;
  assign add_signext_37 = $signed({{2{product20[22]}}, product20});
  assign add_temp_18 = add_signext_36 + add_signext_37;
  assign sum19 = add_temp_18[24:0];

  assign add_signext_38 = sum19;
  assign add_signext_39 = $signed({{2{product21[22]}}, product21});
  assign add_temp_19 = add_signext_38 + add_signext_39;
  assign sum20 = add_temp_19[24:0];

  assign add_signext_40 = sum20;
  assign add_signext_41 = $signed({{2{product22[22]}}, product22});
  assign add_temp_20 = add_signext_40 + add_signext_41;
  assign sum21 = add_temp_20[24:0];

  assign add_signext_42 = sum21;
  assign add_signext_43 = $signed({{2{product23[22]}}, product23});
  assign add_temp_21 = add_signext_42 + add_signext_43;
  assign sum22 = add_temp_21[24:0];

  assign add_signext_44 = sum22;
  assign add_signext_45 = $signed({{2{product24[22]}}, product24});
  assign add_temp_22 = add_signext_44 + add_signext_45;
  assign sum23 = add_temp_22[24:0];

  assign add_signext_46 = sum23;
  assign add_signext_47 = $signed({{2{product25[22]}}, product25});
  assign add_temp_23 = add_signext_46 + add_signext_47;
  assign sum24 = add_temp_23[24:0];

  assign add_signext_48 = sum24;
  assign add_signext_49 = $signed({{2{product26[22]}}, product26});
  assign add_temp_24 = add_signext_48 + add_signext_49;
  assign sum25 = add_temp_24[24:0];

  assign add_signext_50 = sum25;
  assign add_signext_51 = $signed({{2{product27[22]}}, product27});
  assign add_temp_25 = add_signext_50 + add_signext_51;
  assign sum26 = add_temp_25[24:0];

  assign add_signext_52 = sum26;
  assign add_signext_53 = $signed({{2{product28[22]}}, product28});
  assign add_temp_26 = add_signext_52 + add_signext_53;
  assign sum27 = add_temp_26[24:0];

  assign add_signext_54 = sum27;
  assign add_signext_55 = $signed({{2{product29[22]}}, product29});
  assign add_temp_27 = add_signext_54 + add_signext_55;
  assign sum28 = add_temp_27[24:0];

  assign add_signext_56 = sum28;
  assign add_signext_57 = $signed({{2{product30[22]}}, product30});
  assign add_temp_28 = add_signext_56 + add_signext_57;
  assign sum29 = add_temp_28[24:0];

  assign add_signext_58 = sum29;
  assign add_signext_59 = $signed({{2{product31[22]}}, product31});
  assign add_temp_29 = add_signext_58 + add_signext_59;
  assign sum30 = add_temp_29[24:0];

  assign add_signext_60 = sum30;
  assign add_signext_61 = $signed({{2{product32[22]}}, product32});
  assign add_temp_30 = add_signext_60 + add_signext_61;
  assign sum31 = add_temp_30[24:0];

  assign add_signext_62 = sum31;
  assign add_signext_63 = $signed({{2{product33[22]}}, product33});
  assign add_temp_31 = add_signext_62 + add_signext_63;
  assign sum32 = add_temp_31[24:0];

  assign add_signext_64 = sum32;
  assign add_signext_65 = $signed({{2{product34[22]}}, product34});
  assign add_temp_32 = add_signext_64 + add_signext_65;
  assign sum33 = add_temp_32[24:0];

  assign add_signext_66 = sum33;
  assign add_signext_67 = $signed({{2{product35[22]}}, product35});
  assign add_temp_33 = add_signext_66 + add_signext_67;
  assign sum34 = add_temp_33[24:0];

  assign add_signext_68 = sum34;
  assign add_signext_69 = $signed({{2{product36[22]}}, product36});
  assign add_temp_34 = add_signext_68 + add_signext_69;
  assign sum35 = add_temp_34[24:0];

  assign add_signext_70 = sum35;
  assign add_signext_71 = $signed({{2{product37[22]}}, product37});
  assign add_temp_35 = add_signext_70 + add_signext_71;
  assign sum36 = add_temp_35[24:0];

  assign add_signext_72 = sum36;
  assign add_signext_73 = $signed({{2{product38[22]}}, product38});
  assign add_temp_36 = add_signext_72 + add_signext_73;
  assign sum37 = add_temp_36[24:0];

  assign add_signext_74 = sum37;
  assign add_signext_75 = $signed({{2{product39[22]}}, product39});
  assign add_temp_37 = add_signext_74 + add_signext_75;
  assign sum38 = add_temp_37[24:0];

  assign add_signext_76 = sum38;
  assign add_signext_77 = $signed({{2{product40[22]}}, product40});
  assign add_temp_38 = add_signext_76 + add_signext_77;
  assign sum39 = add_temp_38[24:0];

  assign add_signext_78 = sum39;
  assign add_signext_79 = $signed({{2{product41[22]}}, product41});
  assign add_temp_39 = add_signext_78 + add_signext_79;
  assign sum40 = add_temp_39[24:0];

  assign add_signext_80 = sum40;
  assign add_signext_81 = $signed({{2{product42[22]}}, product42});
  assign add_temp_40 = add_signext_80 + add_signext_81;
  assign sum41 = add_temp_40[24:0];

  assign add_signext_82 = sum41;
  assign add_signext_83 = $signed({{2{product43[22]}}, product43});
  assign add_temp_41 = add_signext_82 + add_signext_83;
  assign sum42 = add_temp_41[24:0];

  always @ (posedge clk or posedge reset)
    begin: Output_Register_process
      if (reset == 1'b1) begin
        output_register <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          output_register <= sum42;
        end
      end
    end // Output_Register_process

  // Assignment Statements
  assign filter_out = output_register;
endmodule  // lowPassFir
